package:
  name: merothon
  version: "0.4.2"

source:
  path: .

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - vcf_to_pca=merothon.scripts.VCF_to_PCA:main
    - plot_ld=merothon.scripts.Plot_LD:main
    - plot_genotypes=merothon.scripts.Plot_Genotypes:main
    - permutation_test=merothon.scripts.Permutation_Test:main
    - polarize_vcf=merothon.scripts.Assign_Ancestral_Allele:main
    - calculate_r2=merothon.scripts.Calculate_R2_LD_VCFs:main
    - count_mutations=merothon.scripts.Calculate_Fasta_Mutations:main
    - map_chromosomes=merothon.scripts.Reference_to_Scaffold_ChrID:main
    - subset_snps=merothon.scripts.Subset_SNPs:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10
    - pandas
    - numpy
    - pysam
    - matplotlib-base
    - biopython
    - scikit-allel

test:
  imports:
    - merothon

about:
  home: https://github.com/merondun/merothon
  license: GPL3.0
  summary: 'Genomic utility scripts for various analyses.'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - merondun

